#!/usr/bin/python
{
    'init-field': {
        'procs':        2,
        'filename':     '/tmp/mines.{0}',
        'sec-maxtime':  7200,    # Security timeout (CHANGED 900->7200)
        'sec-maxarea':  10000,  # Maximum allowed area
    },
    'hiscores': {
        'file':         "/var/games/anonymine",
        'entries':      16,     # Top N, how many entries per sublist
        'maxsize':      524288, # Security: Maximum allowed filesize (bytes)
        'use-user':     True,   # List login names
        'use-nick':     True,   # Let players choose their own names
        'nick-maxlen':  100,    # Longest allowed nickname (unicode codepoints)
    },
}
