#!/bin/sh

mkdir garbage-amp
mkdir garbage-amp/pieces
mkdir garbage-amp/photos

cp README tuning schematic.png components-list garbage-amp
cp pcb.blend front.blend back.blend battery-holder.blend battery-door.blend \
    left.blend right.blend top.blend garbage-amp/pieces

# TODO: Add photos

tar -cf garbage-amp.tar garbage-amp
gzip -9 garbage-amp.tar

HEAD https://web.archive.org/save/https://oskog97.com/archive/garbage-amp.tar.gz
cat garbage-amp.tar.gz >/var/www/archive/garbage-amp.tar.gz
rm -r garbage-amp
rm garbage-amp.tar.gz
